### ISSUE TITLE
Can't use the volume with more than one container

### ISSUE THREAD

**Issue by muehle28** [vieux/docker-volume-sshfs#12]
When the mounted sshfs volume is used on more than one container the following error is raised.

> Error while mounting volume '/var/lib/docker/plugins/.../rootfs/mnt/_sshfs/...': VolumeDriver.Mount: exit status 1

If the volume is used with just one container the plugin works fine.

**Comment by vieux** [comment]
@muehle28 thanks, I;ll take a look

**Comment by vieux** [comment]
@muehle28 fixed in https://github.com/vieux/docker-volume-sshfs/commit/fe8b54f13499e3b88a2faa8e60526d37acf66b49
