### ISSUE TITLE
Bug: in-memory v.connections value lost when it crashes and restarted

### ISSUE THREAD

**Issue by ghostplant** [vieux/docker-volume-sshfs#14]
When multi-containers share volume of same name, crash of plugin driver will be unable to correctly handle their umount once it is restarted.

**Comment by vieux** [comment]
@ghostplant I'll look into it, any hints on why the plugin crashed ?

**Comment by vieux** [comment]
@ghostplant I believe it's fixed by https://github.com/vieux/docker-volume-sshfs/commit/fe8b54f13499e3b88a2faa8e60526d37acf66b49

**Comment by ghostplant** [comment]
Do you think it is legal when exiting a container with 'volume xxx is currently used by a container' reported?

**Comment by ghostplant** [comment]
Besides, latest upstream builds a docker-plugin-driver binary failing to run on ubuntu due to 'libc.musl-x86_64.so.1 => not found'.

**Comment by ghostplant** [comment]
I think API should contain req.{Name, ID, **nameIsShared**}. Thus it will simplify most of 3rd-party plugin driver without any kind of `counter` bugs.

**Comment by ghostplant** [comment]
**Case 1:**
docker volume plugin install vieux/sshfs
docker volume create -d vieux/sshfs -o sshcmd=a@0.0.0.0:/tmp -o password=123 sshvolume
docker run -it --name n1 -d -v sshvolume:/ssh alpine:3.4 sleep 1h
killall docker-volume-sshfs

$ docker volume rm sshvolume
Error response from daemon: Unable to remove volume, volume still in use: remove sshvolume: volume is in use - [2f56f17a3bba9a2f1ed72ae3db495e2417b1219ec17a4b324445e3c481551209]
$ docker kill n1 && docker rm n1
$ docker volume rm sshvolume
Error response from daemon: Error while removing volume sshvolume: remove sshvolume: VolumeDriver.Remove: remove /mnt/volumes/59faf0aa8522fecd92fd6a1af9c91230: device or resource busy

**Comment by ghostplant** [comment]
**Case 2:**
$ docker volume plugin install vieux/sshfs
$ docker volume create -d vieux/sshfs -o sshcmd=**a@0.0.0.0:/tmp** -o password=**123** sshvolume
$ docker run -it --name n1 -d -v sshvolume:/ssh alpine:3.4 sleep 1h
$ docker run -it --name n2 -d -v sshvolume:/ssh alpine:3.4 sleep 1h
$ killall docker-volume-sshfs
$ docker kill n1 && docker rm n1
$ docker kill n2 && docker rm n2
$ docker volume rm sshvolume
Error response from daemon: Unable to remove volume, volume still in use: remove sshvolume: volume is in use - [2f56f17a3bba9a2f1ed72ae3db495e2417b1219ec17a4b324445e3c481551209]
$ docker volume rm sshvolume
Error response from daemon: Error while removing volume sshvolume: remove sshvolume: VolumeDriver.Remove: volume sshvolume is currently used by a container

**Comment by vieux** [comment]
@ghostplant the old usecase where you have `docker-volume-sshfs` isn't supported anymore.
Can you try with 1.13 and the new style plugins ?

**Comment by ghostplant** [comment]
I did the test on Docker 1.13. See both **Case 1** & **Case 2** contain `docker volume plugin xxx` which is unsupported before 1.13.

**Comment by vieux** [comment]
I believe this issues was fixed in `1.0` the state is now saved on disk.
