### ISSUE TITLE
Permission denied when trying to access from non-root user in container

### ISSUE THREAD

**Issue by koenlek** [vieux/docker-volume-sshfs#17]
Dear @vieux,

I just found out about this great plugin! It really seems to offer exactly what I need. I just ran into a small issue. For reasons I won't explain here, the container that I use has to be run by a non-root user. From that user, I cannot access the mount: if I try to `cd` or access anything in it, I get an error: `bash: cd: <path_name>: Permission denied`. When I switch to root (`sudo -s`), I can cd into it and everything works fine. 

Would there be a way in which I can fix this? I would't mind patching the plugin for my own usecase, if you can point me the right direction...

By the way, I tried `sudo chown -R <user>:<user> <path_name>` and  `sudo chown <user>:<user> <path_name>`, but both don't work...

**Comment by koenlek** [comment]
It turns out that you need to use the `-o allow_other` option of `sshfs`. I also figured out more or less how I could add this to the plugin by patching `main.go`. For now, there is even a quick and dirty fix to get it working using the current version of the plugin:

```
docker volume create -d vieux/sshfs:latest -o sshcmd="-o allow_other <user>@<host>:<path>" -o password=<pw> <vol_name>
```

After my clean fix, it would look like this:

```
docker volume create -d vieux/sshfs:latest -o sshcmd=<user>@<host>:<path> -o allow_other  -o password=<pw> <vol_name>
```

**Comment by chrsch** [comment]
@koenlek Great you already provided this PR! This also will fix #15

**Comment by vieux** [comment]
fixed in https://github.com/vieux/docker-volume-sshfs/pull/18

**Comment by f1d** [comment]
@koenlek !!!! Great you already provided this PR! This also will fix !!!
