### ISSUE TITLE
Always getting "... sshfs.sock: connect: no such file or directory" in docker 17.03-ce (swarm mode) using rpi and rasbian v8/jessie

### ISSUE THREAD

**Issue by giminni** [vieux/docker-volume-sshfs#19]
I tried to create a volume and I got always:
**sshfs.sock: connect: no such file or directory** 
I'm using swarm mode 17.03.0-ce build 60ccb22 with rpi under rasbian v8/jessie
connecting to a rpi using also the same debian/jessie environment.

fuse and ssh is installed on target and swarm hosts

**Comment by rootsongjc** [comment]
+1 Where the `socketAddress = "/run/docker/plugins/sshfs.sock"` used?

**Comment by vieux** [comment]
@giminni @rootsongjc I'm not able to reproduce. do you still have the issue ?

**Comment by rootsongjc** [comment]
The problem has been solved. Building the plugin on my Mac but running on CentOS so that the `.sock` doesn't created.

**Comment by vieux** [comment]
@rootsongjc how are you building the plugin, and why aren't you using the official one, `vieux/sshfs:latest` ?

**Comment by rootsongjc** [comment]
@vieux yes, I build the plugin manually, and it is OK for me.

**Comment by vieux** [comment]
@rootsongjc not sure I understand, but looks like you're not building it correctly

**Comment by vieux** [comment]
see https://github.com/vieux/docker-volume-sshfs/blob/master/Dockerfile#L5 , you have to mkdir the folder

**Comment by rootsongjc** [comment]
@vieux This is not a problem, I have solved it. Thank you.

**Comment by mike391** [comment]
@rootsongjc Can you please enlighten us on how you solved this?

**Comment by rootsongjc** [comment]
Sorry, @mike391 This is an issue of two years ago, I just flag it was solved but I didn't use it anymore.

**Comment by abuisman** [comment]
I am running into this on a raspberrypi right now. Any ideas on how to fix? Rebuild on device itself?

**Comment by ogmundur** [comment]
If you build the plugin on the Raspberry Pi itself, it works fine. Here were the steps I performed (on the Raspberry Pi):

`git clone https://github.com/vieux/docker-volume-sshfs.git`
`cd docker-volume-sshfs`
`make all`
`make enable`

**Comment by antontre1** [comment]
@ogmundur  thanks a lot, did it too and works fine.
May I ask you how did you decide to do this ? I mean what drove you to the conclusion to rebuild it on this arm machine to make it work?
again thx a lot

**Comment by antontre1** [comment]
@ogmundur  just one basic question : how do you integrate the SSH private key when you launch the make all?
I mean, I didn't find way to add SSH private key option when I use makefile.

Thanks a lot

**Comment by ogmundur** [comment]
Very welcome. I am afraid I just stumbled on this via trial and error. I haven't tried adding a private key yet (I just used a password).

**Comment by antontre1** [comment]
Argh Finally found the correct way to make it happen on my system (one rpi as a server, one mac hosting the remote volume), thanks to this do not have to have to share my password.

1. installing `vieux/sshfs` with make all (as @ogmundur recommended ON ALL MACHINES, for me : rpi (where my server is) and mac (to put my volume shared)
2.  be sure to have a root keygene already done (for me : in Pi), and identify the folder where rsa are : `/root/.ssh/`, ensure the public key has been shared (for me with : mac), otherwise have a look at : https://www.raspberrypi.org/documentation/remote-access/ssh/passwordless.md)
3. (for me on pi) `docker plugin disable vieux/sshfs:next`
4. (for me on pi) `docker plugin set vieux/sshfs:next sshkey.source=/root/.ssh/` (see this : [https://blog.raphaelpiccolo.com/post/850](url))
5. (for me on pi) `docker plugin enable vieux/sshfs:next`
6. (for me on pi) and this is my docker-compose.yml to be launched : 

```
version: "3"

services:
  myserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - COMMONVOLUME:/usr/share/nginx/html

volumes:
  COMMONVOLUME:
    driver: "vieux/sshfs:next"
    driver_opts:
      sshcmd: <USERREMOTE>@<IPREMOTE>:/REMOTEPATH/WHERE/THE/FOLDER/TOBESYNCFORVOLUME/IS
      allow_other: ""
```

**Comment by 24HOURSMEDIA** [comment]
> If you build the plugin on the Raspberry Pi itself, it works fine. Here were the steps I performed (on the Raspberry Pi):
> 
> `git clone https://github.com/vieux/docker-volume-sshfs.git`
> `cd docker-volume-sshfs`
> `make all`
> `make enable`

Had the same problem with rpi4 and ubuntu server. This answer solved it.

**Comment by more-pepsi** [comment]
> If you build the plugin on the Raspberry Pi itself, it works fine. Here were the steps I performed (on the Raspberry Pi):
> 
> `git clone https://github.com/vieux/docker-volume-sshfs.git` `cd docker-volume-sshfs` `make all` `make enable`

How can I set the sshkey.source flag when using this method?

as a hack fix i've set ```docker plugin set eae sshkey.source=/home/bill/.ssh/```

**Comment by engrjislam** [comment]
> > If you build the plugin on the Raspberry Pi itself, it works fine. Here were the steps I performed (on the Raspberry Pi):
> > `git clone https://github.com/vieux/docker-volume-sshfs.git`
> > `cd docker-volume-sshfs`
> > `make all`
> > `make enable`
> 
> Had the same problem with rpi4 and ubuntu server. This answer solved it.

Also works in `Nvidia Jetson Xavier`.
