### ISSUE TITLE
ssh config files and/or private keys

### ISSUE THREAD

**Issue by mattzuba** [vieux/docker-volume-sshfs#24]
Is there any plans on allowing the possibility of using private keys instead of passwords, and maybe ssh config files as well?  Kind of related to #22

**Comment by mattzuba** [comment]
So I made this minor change and rebuilt the plugin and created the source directory on the host with 0700 perms, added a config file (and a private key that is used by a config entry) and it works great!  If there aren't any security implications in this (I don't think there are), I can submit a PR or you can just apply this change or a variation of it.  Allowing this would pretty much solve #22 since private keys could then be used in lieu of passwords.

```diff
diff --git a/config.json b/config.json
index b47628d..4e88ad7 100644
--- a/config.json
+++ b/config.json
@@ -37,6 +37,14 @@
             ],
             "source": "/var/lib/docker/plugins/",
             "type": "bind"
+        },
+        {
+            "destination": "/root/.ssh",
+            "options": [
+                "bind"
+            ],
+            "source": "/var/lib/docker-volume-sshfs",
+            "type": "bind"
         }
     ],
     "network": {
```

**Comment by stevvooe** [comment]
@cyli PTAL

@mattzuba We'll take a closer look at this. I haven't thought about this one in a little while. As long as the image doesn't pick up sensitive data from the host and sensitive data is not transmitted in the plugin, then this should work. I think the main user issue with this is that they have to create `/var/lib/docker-volume-sshfs` on every host, which can be confusing or problematic, albeit, way better than distributing passwords.

**Comment by prologic** [comment]
Can docker secrets be used instead here?

**Comment by cyli** [comment]
As I remember from https://github.com/vieux/docker-volume-sshfs/pull/10, we didn't want all keys to be shared by every instance of a container that required an SSHFS volume?  But the key material is not visible to those containers, just the volume plugin container.

@prologic That would probably be a great way to go, since that would mean you wouldn't have to create a mount directory on every node. It's not currently possible, however, as you can't install plugins on swarm currently, but it's being worked on.  (Please see https://github.com/moby/moby/pull/33575 and https://github.com/docker/swarmkit/pull/2305)

**Comment by mattzuba** [comment]
The only downfall I see with secrets, at least with my use case (ci/cd containers) is that it (currently) requires Swarm, and I don't know that ci/cd containers are a good use of Swarm.

@cyli - since this minor change doesn't allow someone mounting a volume to specify which key to use, I don't think that would be an issue here.  In order to use a key for a particular remote server, the ssh config file would need a host entry in it pointing to the key to use, so whoever manages the docker host and has write access to /var/lib/docker-volume-sshfs would essentially be in control of what keys are used to connect to which remote servers (unless someone dropped an id_rsa file in there which would then be picked up by default by the ssh client in the plugin container, which may be desirable in some use cases).

**Comment by cyli** [comment]
@mattzuba Makes sense.  The only other possible issue I could see with this is that if we did want to use secrets, trying to bind an `id_rsa` file or some such into `/root/.ssh` which could possibly conflict with the default bind mount.
