### ISSUE TITLE
Support for disabled compression 

### ISSUE THREAD

**Issue by glazeddonut** [vieux/docker-volume-sshfs#27]
I would suggest that you add the sshfs options 

```
-o Ciphers=arcfour 
-o Compression=no
```

which according to some can speed up sshfs a great deal - if you don't need encryption and compression.

https://www.smork.info/blog/2013/04/24/entry130424-163842.html

**Comment by vieux** [comment]
Thanks for the idea. In the next version I'll simply passthrough every `-o`

**Comment by vieux** [comment]
@glazeddonut see https://github.com/vieux/docker-volume-sshfs/pull/29
