### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by thalesfsp** [vieux/docker-volume-sshfs#3]
Two PR's needs merges also when running `go get` this error occour:

```bash
package github.com/docker/docker/pkg/sockets: cannot find package "github.com/docker/docker/pkg/sockets" in any of:
	/usr/local/Cellar/go/1.5.2/libexec/src/github.com/docker/docker/pkg/sockets (from $GOROOT)
	/Users/thalesfsp/repos/go/src/github.com/docker/docker/pkg/sockets (from $GOPATH)
```

@vieux

**Comment by vieux** [comment]
@thalesfsp thanks for the reminder, I merged the 2 PRs and will update the code asap to rely on https://github.com/docker/go-plugins-helpers instead of https://github.com/calavera/dkvolume

**Comment by assembledadam** [comment]
Wanted to use this but getting the same error. Is there a workaround for now?

**Comment by thalesfsp** [comment]
@vieux let me know when it will be ready, we have plans to use here, in the office, but it's even working.. so. Thanks!

**Comment by vieux** [comment]
@assembledadam @thalesfsp it should be good. I just pushed https://github.com/vieux/docker-volume-sshfs/commit/87bf704a4b18d0d19e9379e3f64457e4fe47ba45 that uses the right dependencies

**Comment by thalesfsp** [comment]
@vieux thanks!
