### ISSUE TITLE
cannot get to work with ssh keys

### ISSUE THREAD

**Issue by victort** [vieux/docker-volume-sshfs#43]
hi,

I've set up an account on my destination system, the `authorized_keys` file includes the ssh identity `docker volume create` will use (i.e.  `volumeuserkey.pub`). However, _no permutation_ of

`docker volume create -d vieux/sshfs -o sshcmd=volumeuser@volumehost:/home/volumehome/volume -o reconnect -o IdentityFile=$(pwd)/PROJECTS/secrets/volumeuserkey volumemount` 

..will work. Even though the `volumeuserkey` has no passphrase, and is in the directory where the `IdentityFile` is pointing. 

This does not work whether I use:
`docker plugin install sshkey.source=$(pwd)/PROJECTS/secrets/ DEBUG=1 ` 
or 
`docker plugin set vieux/sshfs:latest sshkey.source=$(pwd)/PROJECTS/secrets/` 
...or any combination thereof.

(neither $(pwd) prefix nor absolute directory name work)

What am I missing/doing wrong?

to be clear, everything Works Fine™ if I use `-o password=${VOLUMEUSERPASSWORD}`, which i'd rather not do. 

Additionally, just sshing (or using sshfs manually) to the destination system with the `volumeuser` creds works as expected (i.e. ssh key negotiated shell prompt/mount) 

```
debian stretch/buster

$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

thanks in advance,
-m

**Comment by victort** [comment]
nm. i get it now. the key goes -in- the image.

**Comment by jamiejackson** [comment]
Could you clarify what you ended up doing?

**Comment by yijing1998** [comment]
I ran into the same problem, can you tell me how to do with it, Thank you! @victort
