### ISSUE TITLE
Use driver_opts instead of volume name

### ISSUE THREAD

**Issue by niieani** [vieux/docker-volume-sshfs#6]
The driver doesn't work with `docker-compose`, because there is no way to create a named volume with a `#` in it. Instead of this hacky workaround it would be best to use the native `options`, e.g. like this:

```shell
docker volume create -d sshfs -o host=1.2.3.4 -o port=22 -o mountpoint=/data --name=awesome-volume
```

As an example, see: https://github.com/CWSpear/local-persist

**Comment by vieux** [comment]
@niieani I updated the plugins recently, thanks.
