### ISSUE TITLE
Volume not created 

### ISSUE THREAD

**Issue by courcelm** [vieux/docker-volume-sshfs#9]
It seems the volume is not created after issuing the docker volume create command.

docker volume ls   is not showing anything

Here is my docker version:
Client:
 Version:      1.12.2-rc3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   cb0ca64
 Built:        Thu Oct  6 22:10:40 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   cb0ca64
 Built:        Thu Oct  6 22:10:40 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by vieux** [comment]
@courcelm can you reproduce with 1.13.x ?

**Comment by courcelm** [comment]
It works with 1.13
